# ============================================================
# Build the Fortran test program.
#
# This Makefile is called by build.bat after LIS is available.
# ============================================================

# Compiler and project paths.
FC = ifx
SOURCE = src\main.F90
OBJECT = build\obj\main.obj
PROGRAM = build\bin\lis_test.exe
LIS_INCLUDE = ext\lis\include
LIS_LIBRARY = ext\lis\win\lis.lib

# The default target builds the program.
all: directories $(PROGRAM)

# Create the folders used for generated files.
directories:
	if not exist build\obj mkdir build\obj
	if not exist build\bin mkdir build\bin

# Compile the Fortran source into an object file.
# c: compile but do not create an executable
# fpp: run the Fortran preprocessor. Useful for including LIS header files.
$(OBJECT): $(SOURCE)
	$(FC) /c /fpp /I$(LIS_INCLUDE) $(SOURCE) /object:$(OBJECT)

# Link the object file with LIS to create the executable.
$(PROGRAM): $(OBJECT) $(LIS_LIBRARY)
	$(FC) $(OBJECT) $(LIS_LIBRARY) /exe:$(PROGRAM)

# Remove files generated by this project. LIS is not removed.
clean:
	if exist build rmdir /s /q build
